version: '3.9'

services:
  dynamodb:
    build:
      context: ./dynamodb
    ports:
      - 8000:8000
    volumes:
      - db:/home/dynamodblocal/db
  admin:
    image: aaronshaf/dynamodb-admin
    environment:
      - DYNAMO_ENDPOINT=dynamodb:8000
    ports:
      - 8001:8001
    depends_on:
      - dynamodb
volumes:
  db:
